### PR TITLE
Add musl support

### PR DESCRIPTION
**Pull request by giulio-coa**
## Thank you for your contribution to the Pi-hole Community! 

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**
 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions

---
- **What does this PR aim to accomplish?:**

I would like to be able to add support for `musl` to the various architectures present

- **How does this PR accomplish the above?:**

I have added support for almost all architectures
Unfortunately there are no alpine images that support `armv4` or `32bit armv8`

- **What documentation changes (if any) are needed to support this PR?:**

*Replace this with a detailed list of any necessary changes*

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by giulio-coa** [comment]
The problem with testing is `https://ftl.pi-hole.net/libraries/*`-like links

**Comment by PromoFaux** [comment]
These are falling over cos the CI is set up for org members I think - sec, will make some adjustments to the workflow

**Comment by PromoFaux** [comment]
Can you rebase on master please and we'll see what's what

**Comment by giulio-coa** [comment]
> Can you rebase on master please and we'll see what's what

Sorry, but I didn't follow your reasoning 😅

**Pull request closed without merging**
