### PR TITLE
Migrate FTL build to Debian Buster

### PR DESCRIPTION
**Pull request by onovy**

### CODE REVIEW

**Comment by dschaper** [comment]
What benefits does `buster` bring to the images used to build binaries?

**Comment by onovy** [comment]
Stretch is going to EOL in 2020. That means, there will be no security updates (only in LTS mode). Because this base Docker image is used as base for pi-hole image, you can end up with unsecure dnsmasq, lighttpd or PHP for example.

Buster is current stable Debian distribution with security and bug support.

**Comment by dschaper** [comment]
These are the images used to build FTL binaries. They are not used for any other purpose. These are not run on user systems.

**Comment by onovy** [comment]
Are you sure? :)
https://github.com/pi-hole/docker-pi-hole/blob/master/Dockerfile.py#L49

**Comment by dschaper** [comment]
Check the files you want to modify, specifically the ones with `ftl-build` in the name.

**Comment by onovy** [comment]
I did. For me it make sense to keep it synced, that's reason why I changed Dockerfiles in this repo.

**Comment by dschaper** [comment]
Okay, I'll let @diginc handle it. For me it's a 'no'.

**Comment by onovy** [comment]
Can you elaborate why? Or are you suggesting to edit just debian-base/Dockerfile in this repo, which is definetly used in user system.

**Comment by dschaper** [comment]
Jessie is currently supported. We know everything works with Jessie. Changing to a new release is not a simple process of just pulling a new image.

**Comment by onovy** [comment]
Right. But it will not be supported soon, so why not move forward? What about second question?

**Comment by dschaper** [comment]
Because the costs are more expensive than the benefits.

**Comment by DL6ER** [comment]
@onovy Have you checked locally that the updated `docker` containers are able to compile `FTL`? Also, have you checked if there is a difference in compiler version between the two?

**Comment by onovy** [comment]
I'm talking about this part:
Or are you suggesting to edit just debian-base/Dockerfile in this repo, which is definitely used in user system.

If it's acceptable for you to upgrade just that part, I can change MR.

Ad cost: It's just about "do it now or later". "Price" is same.

**Comment by onovy** [comment]
> Have you checked locally that the updated `docker` containers are able to compile `FTL`? 

nope. You have CIs, right?

> Also, have you checked if there is a difference in compiler version between the two?

Version of compiler in Buster is newer than in Stretch (obviously :).

**Comment by DL6ER** [comment]
> You have CIs, right?

No sure what this means.

When an update is proposed, it should be checked if it can do the same job. The CI will just happily build your container. It will do whatever you ask it to do unless there is a typo or whatever. It cannot know if it would be able to do what it may be used for later.

**Comment by diginc** [comment]
I don't think we're in any huge rush with security LTS patching being available on Stretch through January, 2022.

A PR like this is the first necessary step to test what happens downstream to the consumers, but because there is some risk downstream I'd prefer:
- Do not replace the stretch images tags with buster using the same docker image:tag scheme
- Create new image names for buster images, leaving the stretch ones available for changes, maintenance, and stability.
- Test the downstream projects:
  - This could be done locally or we could release the new buster tags and make a PR in the FTL/docker-pi-hole repos to test the newly tagged image bases.
  - Once confidence is built up then we can discuss actually deprecating the stretch images with buster versions and re-using the same image ID 
  - *OR* we could just adopt a new scheme that always has the OS codename in docker image tags

**Comment by DL6ER** [comment]
So, I built both containers (`stretch`- and `buster`-based) for the `x86_64` variant locally and confirmed that `FTL` can be compiled correctly on both of them.

**Stretch** (`x86_64`)
```
gcc version 6.3.0
libgmp-dev amd64 2:6.1.2+dfsg-1
nettle-dev amd64 3.3-1+b2
sqlite3 amd64 3.16.2-5+deb9u1
```
**Buster** (`x86_64`)
```
gcc version 8.3.0
libgmp-dev amd64 2:6.1.2+dfsg-4
nettle-dev amd64 3.4.1-1
sqlite3 amd64 3.27.2-3
```

The update in `nettle` and `gcc` makes this upgrade worth it in my view.

The labeling should be sorted out before. I'd say we should be fine with replacing what we have with `buster` images but I'm a technician. Not saying this is good/clean from a more higher management point of view!

**Comment by dschaper** [comment]
Let's figure out if #19 fixes the armel builds, and if that is good then I think we can do this as a v2 of the build images.

**Comment by DL6ER** [comment]
Please merge `master` into your branch to pick up the most recent changes to the containers and we will then check again if the updated containers still compile FTL as expected. We will merge your changes on success.

**Comment by onovy** [comment]
@DL6ER done, thanks

**Comment by lightswitch05** [comment]
Why use `wget` instead of `curl`?

**Comment by lightswitch05** [comment]
I'm not sure what the impact is with the FTL images, but if this is merged to master it will have an immediate impact on the downstream docker-pi-hole builds, as the base image is used there: https://github.com/pi-hole/docker-pi-hole/blob/master/Dockerfile_amd64#L1

I'm all for upgrading to buster, but the way it is done in this PR is does not meet the feature threshold laid out in https://github.com/pi-hole/docker-base-images/pull/14#issuecomment-573166183. At the very least, it should be put into a `dev` branch so that the existing `pihole/debian-base:latest` tag is not replaced.

**Comment by onovy** [comment]
> Why use `wget` instead of `curl`?

See: https://github.com/pi-hole/docker-base-images/pull/14/checks?check_run_id=699537385

**Comment by dschaper** [comment]
I'd prefer `curl`, the issue is with `ca-certificates` and it appears to be related to Ubuntu 18.04 https://bugs.launchpad.net/qemu/+bug/1821006

**Comment by lightswitch05** [comment]
btw, I was able to reproduce this curl error a couple days ago, but I'm unable to reproduce it now. Perhaps it got fixed.

**Comment by dschaper** [comment]
That's highly possible. The error seems to be related to the `qemu` problem at https://github.com/pi-hole/docker-base-images/pull/14/checks?check_run_id=699537385#step:4:532

Might indeed be transient?

**Comment by lightswitch05** [comment]
Shoot... I forgot it was `multiarch/debian-debootstrap:armel-buster-slim` and not just Debian that was messing up. Ok, I think I had a workaround for it, I’ll test it out again tonight and report back

**Comment by lightswitch05** [comment]
Setting `CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` fixes the two failing builds. https://github.com/pi-hole/docker-base-images/pull/24/commits/be469628f84e084cecf789f5fec08a7b2dd51679

Looking more at the different FTL images, `wget` is used all over the place, so not sure having to set the CA_BUNDLE is better then just using `wget` like the other images. But anyways, I said I had a workaround, and there it is

**Comment by dschaper** [comment]
We can use `wget` if everything is set to `https` (no `--no-check-certificate` flags). There's a lot of old configurations and commands, not everything is set for a reason or locked in.

**Comment by dschaper** [comment]
@DL6ER Is there anything to modify to use gcc 8?

**Comment by dschaper** [comment]
I can do a new PR that changes `curl` to `wget` and then merge that in to `master`. Once that is done we can have onovy pull in those changes to this PR so this PR doesn't address two issues at one time. I don't think there's any problems with the new gcc or library packages. 

Once this is merged then we can look at #25 for it's new capabilities. 

Is this acceptable?

**Comment by lightswitch05** [comment]
#25 should go before this one, its not really new capabilities but prevents Buster from being forced on the downstream docker-pi-hole project. The changes in `debian-base/Dockerfile` in this PR should be removed. - Or @onovy could just pull my #25 branch into this PR and they can both go together.

**Comment by lightswitch05** [comment]
Basically #25 implements the feature requirements laid out in https://github.com/pi-hole/docker-base-images/pull/14#issuecomment-573166183 by @diginc

**Comment by dschaper** [comment]
If you want to do #14 with #25 that's fine, or #25 first and then address #14.  Does #25 need `wget` fixes?

**Comment by DL6ER** [comment]
> Is there anything to modify to use gcc 8?

No, FTL complies to the C11 standard and should compile with any version of `gcc`.

**Comment by lightswitch05** [comment]
#25 is ready to go as-is. It should have zero immediate impact on downstream projects as any existing tags are still Stretch. When downstream is ready to start trying the buster images, then the new tags introduced by #25 will be ready for use.

**Comment by DL6ER** [comment]
Superseded by #31

**Pull request closed without merging**
