### PR TITLE
Add web-build/Dockerfile

### PR DESCRIPTION
**Pull request by DL6ER**
Note that this PR is still lacking the necessary changes to `.circleci/config.yml

### CODE REVIEW

**Comment by DL6ER** [comment]
@dschaper Do we need the .circleci changes here?

**Comment by dschaper** [comment]
Yep, there's an image on Docker Hub for it already but if you want updates to build then it need to have the CI instructions done.

**Comment by lightswitch05** [comment]
Once #17 is merged, I would be happy to complete the work on this to make the builds automatic. It would also serve as a great test that #17 is working as expected in respect to pull requests from outside repos

**Comment by dschaper** [comment]
See #18

**Pull request closed without merging**
