### PR TITLE
Add web-build to docker actions

### PR DESCRIPTION
**Pull request by lightswitch05**
* Adds the web-build from #12 to the github actions builder.
* This pull request also tests the pull-request logic of the github actions added by #17. The expected behavior is that a build will be triggered, but it will not attempt to tag and push the images.

### CODE REVIEW

**Comment by lightswitch05** [comment]
All checks passed! Built all images (including web-build), and did not attempt to push them to docker hub.

**Comment by lightswitch05** [comment]
I just noticed that this `web-build` image also lives over at: https://github.com/pi-hole/web/blob/master/docker/Dockerfile

Looking at [Dockerhub](https://hub.docker.com/r/pihole/web-build/dockerfile), the last build was 5 days ago, using `v0.12.0`. It looks like this pull request has it set for `v0.13.0`.

Given the different repos and that there is recent build using a different version, I have no idea if this is still a valid pull request or not. Perhap @DL6ER - the original author of #12 can weigh in on that.

My primary goal to test that pull requests will trigger github actions to build without trying to push has been completed.

**Comment by lightswitch05** [comment]
I don't think the intention is to have this image build here any longer. Perhaps should close #12 as well.

**Comment by dschaper** [comment]
I think the idea was to move from /pi-hole/web to this repo. We'd like to have all the base images and docker build processes to be in one place.

**Comment by dschaper** [comment]
`v.0.13.0` is the version that should be used, as standardized in the other images that use that utility.

https://github.com/pi-hole/docker-base-images/blob/master/ftl-build/x86_64/Dockerfile#L4

**Comment by lightswitch05** [comment]
I closed this due to the uncertainties listed here: https://github.com/pi-hole/docker-base-images/pull/18#issuecomment-596861071

If #12 is still valid, then this pull request is certainly still valid was well. Seeing active builds being created for this image over at https://github.com/pi-hole/web/blob/master/docker/Dockerfile lead me to believe that this was a stale pull request.

**Comment by dschaper** [comment]
This should supersede #12, correct?

**Comment by lightswitch05** [comment]
Yes, it includes #12

**Comment by dschaper** [comment]
We can merge this, I don't think it's going to get a whole lot of use in the near future, but at least it puts everything in one repo.

**Comment by lightswitch05** [comment]
Looks like this web-build image has different creds: https://github.com/pi-hole/docker-base-images/runs/706791244#step:5:30

**Comment by dschaper** [comment]
Hrm, let me check.

**Comment by dschaper** [comment]
Fixed.

**Pull request merged**
