### PR TITLE
Add libidn to ftl-build images

### LINKED ISSUE #13: Add libidn to container images.
See https://github.com/pi-hole/FTL/pull/673

### PR DESCRIPTION
**Pull request by dschaper**
Fixes #13

### CODE REVIEW

**Comment by dschaper** [comment]
I think these actually built and pushed to hub.docker.com as images? I'm not sure if that is the intended process or if only tagged images are supposed to build. Can we keep it so that only master branch or versioned tags are actually pushed?

**Comment by diginc** [comment]
> I think these actually built and pushed to hub.docker.com as images? I'm not sure if that is the intended process or if only tagged images are supposed to build. Can we keep it so that only master branch or versioned tags are actually pushed?

I think branch builds are pushing to :latest instead of :<branch name> - PRs from those without push access to this repo will never deploy.

**Comment by dschaper** [comment]
Should I tag 7ea549e as `v2` and push the tag here?

**Comment by dschaper** [comment]
`ftl` builds are pinned to version 1 now. https://github.com/pi-hole/FTL/pull/684

What do I need to do to make this v2? Looking at https://github.com/pi-hole/docker-base-images/blob/master/.circleci/config.yml#L19 I don't see where the version is actually added to the image name?

**Comment by diginc** [comment]
I used the [release](https://github.com/pi-hole/docker-base-images/releases) page to tag v1 in github and CI pushed it to hub.

You're looking at the right code, circle reads the tag info from git, also see : https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by diginc** [comment]
Also you shouldn't release non master commits.  So I'll merge.

**Comment by dschaper** [comment]
Doesn't `IMAGE="${IMAGE/:/:${CIRCLE_TAG}-}"` end up being something like `IMAGE=IMAGE::CIRCLE-TAG-` with the double colons?

**Pull request merged**
